name: Automated Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Run xUnit Tests
      run: dotnet test "ЛБ3/Saribehian/FitVisionTests/FitVisionTests.csproj"