name: Automated Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x

    - name: Run Saribehian Tests
      run: dotnet test "ЛБ3/Saribehian/FitVisionTests/FitVisionTests.csproj"

    - name: Run Voloshyn Tests
      run: dotnet test "ЛБ3/Voloshyn/FitVisionTests/FitVisionTests.csproj"

    - name: Run Bondar Tests
      run: dotnet test "ЛБ3/Bondar/FitVisionTests/FitVisionTests.csproj"
